### ISSUE TITLE
NFT - query ownership

### ISSUE THREAD

**Issue by irene-bbox** [BalloonBox-Inc/NEARoracle-Contract#31]
### Description
implement some functions to query the NFT ownership of wallet addresses: who owns what? / who are tokens owned by?

### Tasks
- [x] ownership **check 1**: return the count of total NFT supply stored in the smart contract (`nft_total_supply`)
- [x] ownership **check 2**: return the list of tokens stored in the smart contract (`nft_tokens`)
- [x] ownership **check 3**: pass in a wallet address and return the count of NFTs owned. (`nft_supply_for_owner`)
- [x] ownership **check 4**: pass in a wallet address and return list of owned tokens (`nft_tokens_for_owner`)
- [x] ownership **check 5**: pass in an NFT and returns the wallet address that owns it - if any (`whose_token`)
